packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.34.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  stylelint: ^16.23.1

catalogs:
  react:
    react: 19.1.1
    react-dom: 19.1.1
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
  storybook:
    storybook: ^9.1.3
    "@storybook/web-components": ^9.1.3
    "@storybook/web-components-vite": ^9.1.3
    "@storybook/react": ^9.1.3
    "@storybook/react-vite": ^9.1.3
    "@storybook/vue3": ^9.1.3
    "@storybook/vue3-vite": ^9.1.3
    "@storybook/addon-docs": ^9.1.3
    "@chromatic-com/storybook": ^4.1.1

onlyBuiltDependencies:
  - esbuild
  - sharp
