packages:
  - "storybooks/*"
  - "examples/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  stylelint: "^16.12.0"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
