packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.39.2
  prettier: ^3.6.2
  tailwindcss: ^3.4.19
  typescript: ^5.9.3
  stylelint: ^16.26.1

catalogs:
  react:
    react: 19.2.3
    react-dom: 19.2.3
    "@types/react": ^19.2.8
    "@types/react-dom": ^19.2.3
  storybook:
    storybook: ^10.2.10
    "@storybook/web-components": ^10.2.10
    "@storybook/web-components-vite": ^10.2.10
    "@storybook/react": ^10.2.10
    "@storybook/react-vite": ^10.2.10
    "@storybook/vue3": ^10.2.10
    "@storybook/vue3-vite": ^10.2.10
    "@storybook/addon-docs": ^10.2.10
    "@chromatic-com/storybook": ^4.1.3

onlyBuiltDependencies:
  - esbuild
  - sharp
