packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.36.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.18
  typescript: ^5.9.3
  stylelint: ^16.24.0

catalogs:
  react:
    react: 19.1.1
    react-dom: 19.1.1
    "@types/react": ^19.1.16
    "@types/react-dom": ^19.1.9
  storybook:
    storybook: ^9.1.10
    "@storybook/web-components": ^9.1.10
    "@storybook/web-components-vite": ^9.1.10
    "@storybook/react": ^9.1.10
    "@storybook/react-vite": ^9.1.10
    "@storybook/vue3": ^9.1.10
    "@storybook/vue3-vite": ^9.1.10
    "@storybook/addon-docs": ^9.1.10
    "@chromatic-com/storybook": ^4.1.1

onlyBuiltDependencies:
  - esbuild
  - sharp
