packages:
  - "storybooks/*"
  - "examples/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.29.0
  prettier: ^3.5.3
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  stylelint: "^16.20.0"

catalogs:
  react18:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
  storybook8:
    "storybook": "^9.0.10"
    "@storybook/addon-essentials": "^8.6.14"
    "@storybook/addon-interactions": "^8.6.14"
    "@storybook/addon-onboarding": "^9.0.10"
    "@storybook/blocks": "^8.6.14"
    "@storybook/test": "^8.6.14"
    "@storybook/web-components": "^9.0.10"
    "@storybook/web-components-vite": "^9.0.10"
    "@storybook/react": "^9.0.10"
    "@storybook/react-vite": "^9.0.10"
    "@storybook/vue3": "^9.0.10"
    "@storybook/vue3-vite": "^9.0.10"
