packages:
  - "storybooks/*"
  - "examples/*"
  - "packages/*"
  - "tooling/*"

catalog:
  eslint: ^9.28.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.17
  typescript: ^5.6.3
  stylelint: "^16.12.0"

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.23
    "@types/react-dom": ^18.3.7
  storybook8:
    "storybook": "^8.6.14"
    "@storybook/addon-essentials": "^8.6.14"
    "@storybook/addon-interactions": "^8.6.14"
    "@storybook/addon-onboarding": "^8.6.14"
    "@storybook/blocks": "^8.6.14"
    "@storybook/test": "^8.6.14"
    "@storybook/web-components": "^8.6.14"
    "@storybook/web-components-vite": "^8.6.14"
    "@storybook/react": "^8.6.14"
    "@storybook/react-vite": "^8.6.14"
    "@storybook/vue3": "^8.6.14"
    "@storybook/vue3-vite": "^8.6.14"
    "eslint-plugin-storybook": "^0.12.0"
