packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.39.2
  prettier: ^3.6.2
  tailwindcss: ^4.2.0
  typescript: ^5.9.3
  stylelint: ^16.26.1

catalogs:
  react:
    react: 19.2.3
    react-dom: 19.2.3
    "@types/react": ^19.2.8
    "@types/react-dom": ^19.2.3
  storybook:
    storybook: ^9.1.17
    "@storybook/web-components": ^9.1.17
    "@storybook/web-components-vite": ^9.1.17
    "@storybook/react": ^9.1.17
    "@storybook/react-vite": ^9.1.17
    "@storybook/vue3": ^9.1.17
    "@storybook/vue3-vite": ^9.1.17
    "@storybook/addon-docs": ^9.1.17
    "@chromatic-com/storybook": ^4.1.3

onlyBuiltDependencies:
  - esbuild
  - sharp
