packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.32.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  stylelint: ^16.22.0

catalogs:
  react:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
  storybook:
    storybook: ^8.6.14
    '@storybook/addon-essentials': ^8.6.14
    '@storybook/addon-interactions': ^8.6.14
    '@storybook/addon-onboarding': ^8.6.14
    '@storybook/blocks': ^8.6.14
    '@storybook/test': ^8.6.14
    '@storybook/web-components': ^8.6.14
    '@storybook/web-components-vite': ^8.6.14
    '@storybook/react': ^8.6.14
    '@storybook/react-vite': ^8.6.14
    '@storybook/vue3': ^8.6.14
    '@storybook/vue3-vite': ^8.6.14
    '@chromatic-com/storybook': ^3.2.7

onlyBuiltDependencies:
  - esbuild
  - sharp
