packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.39.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  stylelint: ^16.25.0

catalogs:
  react:
    react: 19.2.0
    react-dom: 19.2.0
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
  storybook:
    storybook: ^9.1.16
    "@storybook/web-components": ^9.1.16
    "@storybook/web-components-vite": ^9.1.16
    "@storybook/react": ^9.1.16
    "@storybook/react-vite": ^9.1.16
    "@storybook/vue3": ^9.1.16
    "@storybook/vue3-vite": ^9.1.16
    "@storybook/addon-docs": ^9.1.16
    "@chromatic-com/storybook": ^4.1.2

onlyBuiltDependencies:
  - esbuild
  - sharp
