packages:
  - storybooks/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.32.0
  prettier: ^3.6.2
  tailwindcss: ^3.4.17
  typescript: ^5.9.2
  stylelint: ^16.23.0

catalogs:
  react:
    react: 19.1.1
    react-dom: 19.1.1
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
  storybook:
    storybook: ^9.1.1
    '@storybook/addon-essentials': ^8.6.14
    '@storybook/addon-interactions': ^8.6.14
    '@storybook/addon-onboarding': ^9.1.1
    '@storybook/blocks': ^8.6.14
    '@storybook/test': ^8.6.14
    '@storybook/web-components': ^9.1.1
    '@storybook/web-components-vite': ^9.1.1
    '@storybook/react': ^9.1.1
    '@storybook/react-vite': ^9.1.1
    '@storybook/vue3': ^9.1.1
    '@storybook/vue3-vite': ^9.1.1
    '@chromatic-com/storybook': ^3.2.7

onlyBuiltDependencies:
  - esbuild
  - sharp
