packages:
  - "packages/*"
  - "examples/*"
  - tooling/*

catalog:
  eslint: ^9.39.2
  prettier: ^3.6.2
  tailwindcss: ^4.0.0
  "@tailwindcss/vite": ^4.0.0
  tsup: ^8.5.1
  typescript: ^5.9.3
  stylelint: ^16.26.1

onlyBuiltDependencies:
  - esbuild
