/**
 * Copyright 2025 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

export interface ComponentDoc {
  slug: string;
  title: string;
  category: "Display" | "Feedback" | "Form" | "Layout" | "Navigation" | "Overlay";
  description: string;
  primaryExport: string;
  relatedExports: string[];
  notes: string[];
}

export const componentDocs = [
  {
    slug: "accordion",
    title: "Accordion",
    category: "Display",
    description: "Stacks related disclosure sections with controlled or uncontrolled expansion.",
    primaryExport: "Accordion",
    relatedExports: ["AccordionItem", "AccordionTrigger", "AccordionContent"],
    notes: ["Use one item per topic.", "Use `type=\"multiple\"` when more than one section can stay open."],
  },
  {
    slug: "alert",
    title: "Alert",
    category: "Feedback",
    description: "Presents contextual status, warning, or destructive messages inline.",
    primaryExport: "Alert",
    relatedExports: ["AlertTitle", "AlertDescription", "AlertAction"],
    notes: ["Keep alert copy concise.", "Use destructive styling only for high-risk states."],
  },
  {
    slug: "alert-dialog",
    title: "Alert Dialog",
    category: "Overlay",
    description: "Interrupts the flow for confirmations that can change or discard user data.",
    primaryExport: "AlertDialog",
    relatedExports: ["AlertDialogTrigger", "AlertDialogContent", "AlertDialogAction", "AlertDialogCancel"],
    notes: ["Reserve for destructive or irreversible actions.", "Always provide a cancel path."],
  },
  {
    slug: "aspect-ratio",
    title: "Aspect Ratio",
    category: "Layout",
    description: "Keeps media and embedded content within a predictable proportional box.",
    primaryExport: "AspectRatio",
    relatedExports: [],
    notes: ["Use for screenshots, video, cards, and responsive media placeholders."],
  },
  {
    slug: "avatar",
    title: "Avatar",
    category: "Display",
    description: "Shows a person, team, or entity identity with fallback and grouping support.",
    primaryExport: "Avatar",
    relatedExports: ["AvatarImage", "AvatarFallback", "AvatarBadge", "AvatarGroup"],
    notes: ["Always include an accessible fallback.", "Group avatars only when the set represents one shared context."],
  },
  {
    slug: "badge",
    title: "Badge",
    category: "Display",
    description: "Labels status, metadata, counts, and compact classifications.",
    primaryExport: "Badge",
    relatedExports: ["badgeVariants"],
    notes: ["Use short labels.", "Use link styling only when the badge is genuinely navigational."],
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    category: "Navigation",
    description: "Shows the current page location inside a hierarchy.",
    primaryExport: "Breadcrumb",
    relatedExports: ["BreadcrumbList", "BreadcrumbItem", "BreadcrumbLink", "BreadcrumbPage"],
    notes: ["Use `BreadcrumbPage` for the current location.", "Avoid using breadcrumbs as the only navigation."],
  },
  {
    slug: "button",
    title: "Button",
    category: "Form",
    description: "Triggers commands, submissions, and navigation-style actions.",
    primaryExport: "Button",
    relatedExports: ["buttonVariants"],
    notes: ["Choose the variant by action priority.", "Prefer icons plus concise labels for repeated tool actions."],
  },
  {
    slug: "button-group",
    title: "Button Group",
    category: "Form",
    description: "Groups related actions into one compact command cluster.",
    primaryExport: "ButtonGroup",
    relatedExports: ["ButtonGroupSeparator", "ButtonGroupText"],
    notes: ["Keep grouped actions closely related.", "Use separators to clarify mixed action groups."],
  },
  {
    slug: "calendar",
    title: "Calendar",
    category: "Form",
    description: "Supports date selection, ranges, captions, and calendar-specific composition.",
    primaryExport: "Calendar",
    relatedExports: ["CalendarDayButton"],
    notes: ["Pair with form labels when used for input.", "Confirm range behavior in keyboard navigation."],
  },
  {
    slug: "card",
    title: "Card",
    category: "Layout",
    description: "Frames a self-contained piece of content or a compact workflow.",
    primaryExport: "Card",
    relatedExports: ["CardHeader", "CardTitle", "CardDescription", "CardContent", "CardFooter"],
    notes: ["Use cards for repeated items or framed tools.", "Avoid nesting cards inside cards."],
  },
  {
    slug: "carousel",
    title: "Carousel",
    category: "Display",
    description: "Presents horizontally or vertically paged content with controls.",
    primaryExport: "Carousel",
    relatedExports: ["CarouselContent", "CarouselItem", "CarouselPrevious", "CarouselNext"],
    notes: ["Use for small sets where browsing order matters.", "Do not hide critical information in a carousel."],
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    category: "Form",
    description: "Toggles one or more independent boolean choices.",
    primaryExport: "Checkbox",
    relatedExports: [],
    notes: ["Use with a visible label.", "Use radio buttons when exactly one option must be selected."],
  },
  {
    slug: "collapsible",
    title: "Collapsible",
    category: "Display",
    description: "Shows and hides a single content region.",
    primaryExport: "Collapsible",
    relatedExports: ["CollapsibleTrigger", "CollapsibleContent"],
    notes: ["Use for optional details.", "Keep the trigger close to the content it controls."],
  },
  {
    slug: "combobox",
    title: "Combobox",
    category: "Form",
    description: "Combines search, filtering, and selection in one input pattern.",
    primaryExport: "Combobox",
    relatedExports: ["ComboboxInput", "ComboboxList", "ComboboxItem", "ComboboxTrigger"],
    notes: ["Use when the option list is long.", "Prefer select for short static option sets."],
  },
  {
    slug: "command",
    title: "Command",
    category: "Navigation",
    description: "Builds command palettes and searchable action lists.",
    primaryExport: "Command",
    relatedExports: ["CommandInput", "CommandList", "CommandItem", "CommandGroup"],
    notes: ["Group actions by task.", "Include keyboard shortcuts only when they are real app shortcuts."],
  },
  {
    slug: "context-menu",
    title: "Context Menu",
    category: "Overlay",
    description: "Provides contextual actions for a specific target.",
    primaryExport: "ContextMenu",
    relatedExports: ["ContextMenuTrigger", "ContextMenuContent", "ContextMenuItem"],
    notes: ["Mirror essential actions elsewhere for touch and keyboard users.", "Keep destructive actions visually distinct."],
  },
  {
    slug: "dialog",
    title: "Dialog",
    category: "Overlay",
    description: "Opens focused modal content without navigating away from the current page.",
    primaryExport: "Dialog",
    relatedExports: ["DialogTrigger", "DialogContent", "DialogTitle", "DialogDescription"],
    notes: ["Use for focused tasks.", "Keep long flows on full pages when possible."],
  },
  {
    slug: "drawer",
    title: "Drawer",
    category: "Overlay",
    description: "Slides supporting content or short workflows from an edge of the viewport.",
    primaryExport: "Drawer",
    relatedExports: ["DrawerTrigger", "DrawerContent", "DrawerHeader", "DrawerFooter"],
    notes: ["Use for secondary workflows.", "Ensure mobile content remains scrollable."],
  },
  {
    slug: "dropdown-menu",
    title: "Dropdown Menu",
    category: "Overlay",
    description: "Reveals a compact list of actions from a trigger.",
    primaryExport: "DropdownMenu",
    relatedExports: ["DropdownMenuTrigger", "DropdownMenuContent", "DropdownMenuItem"],
    notes: ["Use for actions, not form value selection.", "Place the most common actions first."],
  },
  {
    slug: "empty",
    title: "Empty",
    category: "Feedback",
    description: "Explains an empty state and offers a next action.",
    primaryExport: "Empty",
    relatedExports: ["EmptyHeader", "EmptyTitle", "EmptyDescription", "EmptyContent"],
    notes: ["Explain why the state is empty.", "Offer one clear recovery or creation action."],
  },
  {
    slug: "field",
    title: "Field",
    category: "Form",
    description: "Composes labels, descriptions, errors, and controls into accessible form fields.",
    primaryExport: "Field",
    relatedExports: ["FieldLabel", "FieldDescription", "FieldError", "FieldGroup", "FieldSet"],
    notes: ["Use field primitives to keep form spacing consistent.", "Show errors close to the invalid control."],
  },
  {
    slug: "hover-card",
    title: "Hover Card",
    category: "Overlay",
    description: "Shows rich, non-critical preview content on hover or focus.",
    primaryExport: "HoverCard",
    relatedExports: ["HoverCardTrigger", "HoverCardContent"],
    notes: ["Do not put required actions only inside hover cards.", "Keep preview content short."],
  },
  {
    slug: "input",
    title: "Input",
    category: "Form",
    description: "Captures single-line text, search, numbers, dates, and other native input values.",
    primaryExport: "Input",
    relatedExports: [],
    notes: ["Always pair with a label for forms.", "Use native input types when they improve validation or mobile keyboards."],
  },
  {
    slug: "input-group",
    title: "Input Group",
    category: "Form",
    description: "Combines inputs with prefixes, suffixes, buttons, or helper text.",
    primaryExport: "InputGroup",
    relatedExports: ["InputGroupInput", "InputGroupAddon", "InputGroupButton", "InputGroupText"],
    notes: ["Keep addons brief.", "Use buttons only for actions tightly coupled to the input."],
  },
  {
    slug: "input-otp",
    title: "Input OTP",
    category: "Form",
    description: "Captures one-time passcodes with grouped character slots.",
    primaryExport: "InputOTP",
    relatedExports: ["InputOTPGroup", "InputOTPSlot", "InputOTPSeparator"],
    notes: ["Set a clear maximum length.", "Support paste for full codes."],
  },
  {
    slug: "item",
    title: "Item",
    category: "Display",
    description: "Composes list rows with media, content, metadata, and actions.",
    primaryExport: "Item",
    relatedExports: ["ItemHeader", "ItemContent", "ItemDescription", "ItemActions"],
    notes: ["Use for repeated rows.", "Keep row actions visually secondary unless they are the primary workflow."],
  },
  {
    slug: "kbd",
    title: "Kbd",
    category: "Display",
    description: "Renders keyboard shortcuts and key chords.",
    primaryExport: "Kbd",
    relatedExports: ["KbdGroup"],
    notes: ["Show shortcuts only when they are implemented.", "Use groups for key chords."],
  },
  {
    slug: "label",
    title: "Label",
    category: "Form",
    description: "Associates visible text with a form control.",
    primaryExport: "Label",
    relatedExports: [],
    notes: ["Prefer `htmlFor` with native inputs.", "Keep label text concise and specific."],
  },
  {
    slug: "menubar",
    title: "Menubar",
    category: "Navigation",
    description: "Builds application-style menu bars with nested actions.",
    primaryExport: "Menubar",
    relatedExports: ["MenubarMenu", "MenubarTrigger", "MenubarContent", "MenubarItem"],
    notes: ["Use for app commands, not primary site navigation.", "Group commands consistently."],
  },
  {
    slug: "native-select",
    title: "Native Select",
    category: "Form",
    description: "Styles native select controls while preserving platform behavior.",
    primaryExport: "NativeSelect",
    relatedExports: ["NativeSelectOption", "NativeSelectOptGroup"],
    notes: ["Use for short or medium static option sets.", "Prefer native behavior when mobile platform consistency matters."],
  },
  {
    slug: "navigation-menu",
    title: "Navigation Menu",
    category: "Navigation",
    description: "Creates structured top-level navigation with optional content panels.",
    primaryExport: "NavigationMenu",
    relatedExports: ["NavigationMenuList", "NavigationMenuItem", "NavigationMenuTrigger", "NavigationMenuContent"],
    notes: ["Use for site sections.", "Keep menus shallow and predictable."],
  },
  {
    slug: "pagination",
    title: "Pagination",
    category: "Navigation",
    description: "Navigates through paged result sets.",
    primaryExport: "Pagination",
    relatedExports: ["PaginationContent", "PaginationItem", "PaginationLink", "PaginationNext"],
    notes: ["Use stable URLs for paged content.", "Keep previous and next controls available when possible."],
  },
  {
    slug: "popover",
    title: "Popover",
    category: "Overlay",
    description: "Displays lightweight interactive content anchored to a trigger.",
    primaryExport: "Popover",
    relatedExports: ["PopoverTrigger", "PopoverContent"],
    notes: ["Use for small, contextual controls.", "Prefer dialogs for complex forms."],
  },
  {
    slug: "progress",
    title: "Progress",
    category: "Feedback",
    description: "Communicates task completion as a determinate progress value.",
    primaryExport: "Progress",
    relatedExports: [],
    notes: ["Use an accurate value when progress is determinate.", "Use a spinner for unknown duration."],
  },
  {
    slug: "radio-group",
    title: "Radio Group",
    category: "Form",
    description: "Presents mutually exclusive choices.",
    primaryExport: "RadioGroup",
    relatedExports: ["RadioGroupItem"],
    notes: ["Use when exactly one option is selected.", "Pair every item with a visible label."],
  },
  {
    slug: "resizable",
    title: "Resizable",
    category: "Layout",
    description: "Creates resizable panel groups for split views and editors.",
    primaryExport: "ResizablePanelGroup",
    relatedExports: ["ResizablePanel", "ResizableHandle"],
    notes: ["Use persistent sizes for productivity surfaces.", "Keep minimum panel sizes usable."],
  },
  {
    slug: "scroll-area",
    title: "Scroll Area",
    category: "Layout",
    description: "Provides styled scrolling regions with consistent scrollbar treatment.",
    primaryExport: "ScrollArea",
    relatedExports: ["ScrollBar"],
    notes: ["Use only when a nested scroll region is intentional.", "Avoid trapping long page content unnecessarily."],
  },
  {
    slug: "select",
    title: "Select",
    category: "Form",
    description: "Provides a custom single-value selection control.",
    primaryExport: "Select",
    relatedExports: ["SelectTrigger", "SelectContent", "SelectItem", "SelectValue"],
    notes: ["Use for compact controlled selection.", "Prefer combobox when search is needed."],
  },
  {
    slug: "separator",
    title: "Separator",
    category: "Layout",
    description: "Visually separates related content sections or menu groups.",
    primaryExport: "Separator",
    relatedExports: [],
    notes: ["Use sparingly.", "Do not use separators as a substitute for spacing hierarchy."],
  },
  {
    slug: "sheet",
    title: "Sheet",
    category: "Overlay",
    description: "Shows side-panel content for navigation, filters, or secondary tasks.",
    primaryExport: "Sheet",
    relatedExports: ["SheetTrigger", "SheetContent", "SheetHeader", "SheetFooter"],
    notes: ["Use for side panels and supporting workflows.", "Keep focus management aligned with modal behavior."],
  },
  {
    slug: "sidebar",
    title: "Sidebar",
    category: "Navigation",
    description: "Builds persistent or collapsible app side navigation.",
    primaryExport: "Sidebar",
    relatedExports: ["SidebarProvider", "SidebarHeader", "SidebarContent", "SidebarFooter"],
    notes: ["Use for app navigation, not document footnotes.", "Keep primary destinations scannable."],
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    category: "Feedback",
    description: "Shows a loading placeholder that approximates the final layout.",
    primaryExport: "Skeleton",
    relatedExports: [],
    notes: ["Match the final content dimensions.", "Use for loading, not empty states."],
  },
  {
    slug: "slider",
    title: "Slider",
    category: "Form",
    description: "Lets users choose a number or range from a bounded scale.",
    primaryExport: "Slider",
    relatedExports: [],
    notes: ["Use for approximate values.", "Use inputs when exact values are critical."],
  },
  {
    slug: "sonner",
    title: "Sonner",
    category: "Feedback",
    description: "Provides toast rendering through the shared `Toaster` export.",
    primaryExport: "Toaster",
    relatedExports: [],
    notes: ["Mount one toaster near the app root.", "Use toasts for transient feedback only."],
  },
  {
    slug: "spinner",
    title: "Spinner",
    category: "Feedback",
    description: "Indicates indeterminate loading.",
    primaryExport: "Spinner",
    relatedExports: [],
    notes: ["Use with an accessible label when loading blocks interaction.", "Prefer progress for determinate tasks."],
  },
  {
    slug: "switch",
    title: "Switch",
    category: "Form",
    description: "Toggles a single setting on or off.",
    primaryExport: "Switch",
    relatedExports: [],
    notes: ["Use for immediate settings.", "Use checkbox when the value is part of a form submission group."],
  },
  {
    slug: "table",
    title: "Table",
    category: "Display",
    description: "Displays structured tabular data.",
    primaryExport: "Table",
    relatedExports: ["TableHeader", "TableBody", "TableRow", "TableHead", "TableCell"],
    notes: ["Use real table semantics for tabular data.", "Keep dense data scannable with clear column labels."],
  },
  {
    slug: "tabs",
    title: "Tabs",
    category: "Navigation",
    description: "Switches between related panels in the same context.",
    primaryExport: "Tabs",
    relatedExports: ["TabsList", "TabsTrigger", "TabsContent"],
    notes: ["Use for peer views.", "Do not hide unrelated workflows behind tabs."],
  },
  {
    slug: "textarea",
    title: "Textarea",
    category: "Form",
    description: "Captures multi-line text.",
    primaryExport: "Textarea",
    relatedExports: [],
    notes: ["Use for long-form input.", "Pair with description text when formatting expectations matter."],
  },
  {
    slug: "toggle",
    title: "Toggle",
    category: "Form",
    description: "Represents a pressed or unpressed command state.",
    primaryExport: "Toggle",
    relatedExports: ["toggleVariants"],
    notes: ["Use for toolbar states.", "Use switch for persistent settings."],
  },
  {
    slug: "toggle-group",
    title: "Toggle Group",
    category: "Form",
    description: "Groups related toggle controls for single or multiple selection.",
    primaryExport: "ToggleGroup",
    relatedExports: ["ToggleGroupItem"],
    notes: ["Use `type=\"single\"` for exclusive choices.", "Use `type=\"multiple\"` for independent pressed states."],
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    category: "Overlay",
    description: "Adds short, non-interactive clarification to controls or labels.",
    primaryExport: "Tooltip",
    relatedExports: ["TooltipProvider", "TooltipTrigger", "TooltipContent"],
    notes: ["Keep tooltip text short.", "Do not put required instructions only in tooltips."],
  },
] as const satisfies ComponentDoc[];

export const componentCount = componentDocs.length;

export function getComponentDoc(slug: string) {
  return componentDocs.find((component) => component.slug === slug);
}

export function getComponentsByCategory() {
  const categories = ["Form", "Overlay", "Navigation", "Display", "Feedback", "Layout"] as const;
  return categories.map((category) => ({
    category,
    components: componentDocs.filter((component) => component.category === category),
  }));
}

export function toComponentHref(slug: string) {
  return `/components/${slug}`;
}
