name: Release Test

on:
  push:
    branches:
      - create-tailwindcss-plugin-package
    tags:
      - "v*"
env:
  NPM_TOKEN: ${{ secrets.NPM_JS_LY }}

jobs:
  release:
    name: Release Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build packages
        run: pnpm build

      - name: Write .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_JS_LY }}" >> .npmrc

      - name: Publish
        run: pnpm release --no-git-checks
